---
title: "Reproducibel Document"
author: "rostools"
format: html
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)

post_meal_data <- read.csv2(here::here("data/post-meal-insulin.csv"))
```

## About me

-   Martin Aagaard Lund 
-   OUH

I am a **totally** *sane* person
```{r}
```

## Simple Code
```{r}
```

## Writing R code

2+2

```{r}
2 + 2
```

## Testing for the Git
Lorem Ipsum

## Showing the data

```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continous variable 

```{r}
#| fig-cap: "Distribution of BMI"
#| label: "fig-BMI-histo"
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

See @fig-BMI-histo

## Exercise: discrete plots

```{r}
#| fig-cap: "Groups"
#| label: "fig-Group-plot"
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-Group-plot above for a cool plot!

## Plotting two discrete values

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```

## Side by side plots

```{r fig-bmi-glycemia}
#| fig-cap: "BMI & glycemia, side by side"
#| fig-subcap:
#|  - "Distribution of BMI"
#|  - "Number of glycemic individuals"
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```


## Plotting two continous variables

```{r}
#| fig-cap: "BMI area under the curve"
#| label: fig-bmi-auc-pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```
